FROM node:22-alpine

WORKDIR /app

# copy package dulu agar cache optimal
COPY package*.json ./

# hapus node_modules lama jika ada
RUN rm -rf node_modules

# install dependency fresh di container
RUN npm install

# copy semua source
COPY . .

# pastikan binary executable
RUN chmod -R +x node_modules/.bin

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]