server {
    listen 80;

    server_name _;

    root /usr/share/nginx/html;

    index index.html;

    location = / {
        return 301 /react/;
    }

    location /react/ {
        try_files $uri $uri/ /react/index.html;
    }

    # vite assets
    location /react/assets/ {
        try_files $uri =404;

        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}