name: Deploy React to Shared Hosting Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: Production CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: |
          echo "VITE_BASE_NAME=/" > .env
          npm run build

      - name: Verify Build Output
        run: |
          echo "===== DIST INFO ====="
          ls -lah dist
          echo "SIZE:"
          du -sh dist
          echo "FILES:"
          find dist -type f | wc -l

      - name: Clean Target Directory
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            find /home/${{ secrets.SSH_USER }}/repositories/compro-asputra/public_html/react \
              -mindepth 1 -delete

      - name: Upload Build
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/*"
          target: "/home/${{ secrets.SSH_USER }}/repositories/compro-asputra/public_html/react"


      - name: Verify Upload on Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ls -lah /home/${{ secrets.SSH_USER }}/repositories/compro-asputra/public_html/react

      - name: Commit Frontend Build
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e

            cd /home/${{ secrets.SSH_USER }}/repositories/compro-asputra

            git add public_html/react

            if ! git diff --cached --quiet; then
              git commit -m "🚀 Automated Frontend Deploy ${{ github.sha }}"
              git push origin main
              echo "Deploy committed & pushed successfully"
            else
              echo "No changes detected"
            fi